"""Split cache-eligible raw logs into train and validation manifests.

The module writes JSON/YAML manifests only. Planner-cache ``.npz`` generation
is handled by ``research_v1.data_pipeline.jobs.process_cache``.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Dict, MutableMapping

from research_v1.paths import RESEARCH_ROOT
from research_v1.data_pipeline.raw_split import (
    DEFAULT_CONFIG_OUTPUT_DIR,
    load_json_list,
    scenario_filter_yaml,
    split_log_names,
    write_json,
    write_scenario_filter,
)


DEFAULT_CACHE_LOG_NAMES_PATH = (
    RESEARCH_ROOT / "data_splits" / "boston_raw_seed3407" / "cache_log_names.json"
)
DEFAULT_OUTPUT_DIR = RESEARCH_ROOT / "data_splits" / "boston_raw_seed3407"


def materialize_train_val_split(
    *,
    cache_log_names_path: str,
    output_dir: str,
    config_output_dir: str,
    prefix: str,
    val_ratio: float,
    seed: int,
    group_by: str,
    val_log_limit: int,
    val_group_limit: int,
    write_filters: bool,
) -> Dict[str, object]:
    """Split cache logs into disjoint train/val partitions."""

    cache_log_names = load_json_list(cache_log_names_path)
    split = split_log_names(
        cache_log_names,
        test_ratio=val_ratio,
        seed=seed,
        group_by=group_by,
        test_log_limit=val_log_limit,
        test_group_limit=val_group_limit,
    )
    train_log_names = list(split["cache_log_names"])
    val_log_names = list(split["test_log_names"])
    val_group_ids = list(split["test_group_ids"])

    output_dir_path = Path(output_dir)
    config_output_dir_path = Path(config_output_dir)
    train_path = output_dir_path / "cache_train_log_names.json"
    val_path = output_dir_path / "cache_val_log_names.json"
    val_groups_path = output_dir_path / "cache_val_group_ids.json"
    summary_path = output_dir_path / "cache_train_val_summary.json"

    write_json(train_path, train_log_names)
    write_json(val_path, val_log_names)
    write_json(val_groups_path, val_group_ids)

    summary: MutableMapping[str, object] = dict(split["summary"])  # type: ignore[arg-type]
    summary.update(
        {
            "schema_version": 1,
            "cache_log_names_path": str(Path(cache_log_names_path).resolve()),
            "output_dir": str(output_dir_path.resolve()),
            "config_output_dir": str(config_output_dir_path.resolve()) if write_filters else "",
            "train_log_count": len(train_log_names),
            "val_log_count": len(val_log_names),
            "train_log_names_path": str(train_path.resolve()),
            "val_log_names_path": str(val_path.resolve()),
            "val_group_ids_path": str(val_groups_path.resolve()),
            "val_ratio_requested": float(val_ratio),
            "val_ratio_actual": float(len(val_log_names) / len(cache_log_names)),
        }
    )
    # Keep the original split_log_names fields, but rename their meaning in the
    # summary so readers do not confuse val with the outer simulation-test split.
    summary.pop("cache_log_count", None)
    summary.pop("test_log_count", None)
    summary.pop("cache_group_count", None)
    summary.pop("test_group_count", None)
    summary.pop("test_ratio_requested", None)
    summary.pop("test_ratio_actual", None)
    summary.pop("test_log_limit", None)
    summary.pop("test_group_limit", None)
    summary["val_log_limit"] = int(val_log_limit)
    summary["val_group_limit"] = int(val_group_limit)

    if write_filters:
        train_filter_path = config_output_dir_path / f"{prefix}_train_cache.yaml"
        val_filter_path = config_output_dir_path / f"{prefix}_val_cache.yaml"
        header = (
            "Generated by research_v1.data_pipeline.cache_split.\n"
            f"Source cache log list: {Path(cache_log_names_path).name}\n"
            f"Split is disjoint at {group_by} level with seed={seed}."
        )
        write_scenario_filter(
            train_filter_path,
            scenario_filter_yaml(
                log_names=train_log_names,
                timestamp_threshold_s=None,
                expand_scenarios=True,
                remove_invalid_goals=False,
                shuffle=False,
                header=f"{header}\nTrain cache-generation partition.",
            ),
        )
        write_scenario_filter(
            val_filter_path,
            scenario_filter_yaml(
                log_names=val_log_names,
                timestamp_threshold_s=None,
                expand_scenarios=True,
                remove_invalid_goals=False,
                shuffle=False,
                header=f"{header}\nOffline validation cache-generation partition.",
            ),
        )
        summary["train_cache_filter_path"] = str(train_filter_path.resolve())
        summary["val_cache_filter_path"] = str(val_filter_path.resolve())

    write_json(summary_path, summary)
    summary["summary_path"] = str(summary_path.resolve())
    return dict(summary)


def get_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Split cache logs into train/val raw-log lists")
    parser.add_argument("--cache_log_names_path", type=str, default=str(DEFAULT_CACHE_LOG_NAMES_PATH))
    parser.add_argument("--output_dir", type=str, default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--config_output_dir", type=str, default=str(DEFAULT_CONFIG_OUTPUT_DIR))
    parser.add_argument("--prefix", type=str, default="boston")
    parser.add_argument("--val_ratio", type=float, default=0.10)
    parser.add_argument("--seed", type=int, default=3408)
    parser.add_argument("--group_by", choices=["session", "log"], default="session")
    parser.add_argument("--val_log_limit", type=int, default=0)
    parser.add_argument("--val_group_limit", type=int, default=0)
    parser.add_argument("--write_filters", type=int, default=1)
    return parser.parse_args()


def main() -> None:
    args = get_args()
    summary = materialize_train_val_split(
        cache_log_names_path=args.cache_log_names_path,
        output_dir=args.output_dir,
        config_output_dir=args.config_output_dir,
        prefix=args.prefix,
        val_ratio=args.val_ratio,
        seed=args.seed,
        group_by=args.group_by,
        val_log_limit=args.val_log_limit,
        val_group_limit=args.val_group_limit,
        write_filters=bool(args.write_filters),
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
